
import type { DetailedCategory } from '@/types';

const unsortedCountries: { value: string, label: string }[] = [
  { value: 'AF', label: 'Afganistanas' },
  { value: 'AX', label: 'Alandų Salos' },
  { value: 'AL', label: 'Albanija' },
  { value: 'DZ', label: 'Alžyras' },
  { value: 'AS', label: 'Amerikos Samoa' },
  { value: 'AD', label: 'Andora' },
  { value: 'AO', label: 'Angola' },
  { value: 'AI', label: 'Angilija' },
  { value: 'AQ', label: 'Antarktida' },
  { value: 'AG', label: 'Antigva ir Barbuda' },
  { value: 'AR', label: 'Argentina' },
  { value: 'AM', label: 'Armėnija' },
  { value: 'AW', label: 'Aruba' },
  { value: 'AU', label: 'Australija' },
  { value: 'AT', label: 'Austrija' },
  { value: 'AZ', label: 'Azerbaidžanas' },
  { value: 'BS', label: 'Bahamos' },
  { value: 'BH', label: 'Bahreinas' },
  { value: 'BD', label: 'Bangladešas' },
  { value: 'BB', label: 'Barbadosas' },
  { value: 'BY', label: 'Baltarusija' },
  { value: 'BE', label: 'Belgija' },
  { value: 'BZ', label: 'Belizas' },
  { value: 'BJ', label: 'Beninas' },
  { value: 'BM', label: 'Bermuda' },
  { value: 'BT', label: 'Butanas' },
  { value: 'BO', label: 'Bolivija' },
  { value: 'BQ', label: 'Boneras, Sint Eustatijus ir Saba' },
  { value: 'BA', label: 'Bosnija ir Hercegovina' },
  { value: 'BW', label: 'Botsvana' },
  { value: 'BV', label: 'Buvė Sala' },
  { value: 'BR', label: 'Brazilija' },
  { value: 'IO', label: 'Indijos Vandenyno Britų Sritis' },
  { value: 'BN', label: 'Brunėjus' },
  { value: 'BG', label: 'Bulgarija' },
  { value: 'BF', label: 'Burkina Fasas' },
  { value: 'BI', label: 'Burundis' },
  { value: 'CV', label: 'Žaliasis Kyšulys' },
  { value: 'KH', label: 'Kambodža' },
  { value: 'CM', label: 'Kamerūnas' },
  { value: 'CA', label: 'Kanada' },
  { value: 'KY', label: 'Kaimanų Salos' },
  { value: 'CF', label: 'Centrinės Afrikos Respublika' },
  { value: 'TD', label: 'Čadas' },
  { value: 'CL', label: 'Čilė' },
  { value: 'CN', label: 'Kinija' },
  { value: 'CX', label: 'Kalėdų Sala' },
  { value: 'CC', label: 'Kokosų (Kilingo) Salos' },
  { value: 'CO', label: 'Kolumbija' },
  { value: 'KM', label: 'Komorai' },
  { value: 'CD', label: 'Kongas (Demokratinė Respublika)' },
  { value: 'CG', label: 'Kongas (Respublika)' },
  { value: 'CK', label: 'Kuko Salos' },
  { value: 'CR', label: 'Kosta Rika' },
  { value: 'HR', label: 'Kroatija' },
  { value: 'CU', label: 'Kuba' },
  { value: 'CW', label: 'Kiurasao' },
  { value: 'CY', label: 'Kipras' },
  { value: 'CZ', label: 'Čekija' },
  { value: 'CI', label: 'Dramblio Kaulo Krantas' },
  { value: 'DK', label: 'Danija' },
  { value: 'DJ', label: 'Džibutis' },
  { value: 'DM', label: 'Dominika' },
  { value: 'DO', label: 'Dominikos Respublika' },
  { value: 'EC', label: 'Ekvadoras' },
  { value: 'EG', label: 'Egiptas' },
  { value: 'SV', label: 'Salvadoras' },
  { value: 'GQ', label: 'Pusiaujo Gvinėja' },
  { value: 'ER', label: 'Eritrėja' },
  { value: 'EE', label: 'Estija' },
  { value: 'SZ', label: 'Esvatinis' },
  { value: 'ET', label: 'Etiopija' },
  { value: 'FK', label: 'Folklando Salos' },
  { value: 'FO', label: 'Farerų Salos' },
  { value: 'FJ', label: 'Fidžis' },
  { value: 'FI', label: 'Suomija' },
  { value: 'FR', label: 'Prancūzija' },
  { value: 'GF', label: 'Prancūzijos Gviana' },
  { value: 'PF', label: 'Prancūzijos Polinezija' },
  { value: 'TF', label: 'Prancūzijos Pietų Sritys' },
  { value: 'GA', label: 'Gabonas' },
  { value: 'GM', label: 'Gambija' },
  { value: 'GE', label: 'Gruzija' },
  { value: 'DE', label: 'Vokietija' },
  { value: 'GH', label: 'Gana' },
  { value: 'GI', label: 'Gibraltaras' },
  { value: 'GR', label: 'Graikija' },
  { value: 'GL', label: 'Grenlandija' },
  { value: 'GD', label: 'Grenada' },
  { value: 'GP', label: 'Gvadelupa' },
  { value: 'GU', label: 'Guamas' },
  { value: 'GT', label: 'Gvatemala' },
  { value: 'GG', label: 'Gernsis' },
  { value: 'GN', label: 'Gvinėja' },
  { value: 'GW', label: 'Bisau Gvinėja' },
  { value: 'GY', label: 'Gajana' },
  { value: 'HT', label: 'Haitis' },
  { value: 'HM', label: 'Herdo ir Makdonaldo Salos' },
  { value: 'VA', label: 'Vatikanas' },
  { value: 'HN', label: 'Hondūras' },
  { value: 'HK', label: 'Honkongas' },
  { value: 'HU', label: 'Vengrija' },
  { value: 'IS', label: 'Islandija' },
  { value: 'IN', label: 'Indija' },
  { value: 'ID', label: 'Indonezija' },
  { value: 'IR', label: 'Iranas' },
  { value: 'IQ', label: 'Irakas' },
  { value: 'IE', label: 'Airija' },
  { value: 'IM', label: 'Meno Sala' },
  { value: 'IL', label: 'Izraelis' },
  { value: 'IT', label: 'Italija' },
  { value: 'JM', label: 'Jamaika' },
  { value: 'JP', label: 'Japonija' },
  { value: 'JE', label: 'Džersis' },
  { value: 'JO', label: 'Jordanija' },
  { value: 'KZ', label: 'Kazachstanas' },
  { value: 'KE', label: 'Kenija' },
  { value: 'KI', label: 'Kiribatis' },
  { value: 'KP', label: 'Šiaurės Korėja' },
  { value: 'KR', label: 'Pietų Korėja' },
  { value: 'KW', label: 'Kuveitas' },
  { value: 'KG', label: 'Kirgizija' },
  { value: 'LA', label: 'Laosas' },
  { value: 'LV', label: 'Latvija' },
  { value: 'LB', label: 'Libanas' },
  { value: 'LS', label: 'Lesotas' },
  { value: 'LR', label: 'Liberija' },
  { value: 'LY', label: 'Libija' },
  { value: 'LI', label: 'Lichtenšteinas' },
  { value: 'LT', label: 'Lietuva' },
  { value: 'LU', label: 'Liuksemburgas' },
  { value: 'MO', label: 'Makao' },
  { value: 'MG', label: 'Madagaskaras' },
  { value: 'MW', label: 'Malavis' },
  { value: 'MY', label: 'Malaizija' },
  { value: 'MV', label: 'Maldyvai' },
  { value: 'ML', label: 'Malis' },
  { value: 'MT', label: 'Malta' },
  { value: 'MH', label: 'Maršalo Salos' },
  { value: 'MQ', label: 'Martinika' },
  { value: 'MR', label: 'Mauritanija' },
  { value: 'MU', label: 'Mauricijus' },
  { value: 'YT', label: 'Majotas' },
  { value: 'MX', label: 'Meksika' },
  { value: 'FM', label: 'Mikronezija' },
  { value: 'MD', label: 'Moldova' },
  { value: 'MC', label: 'Monakas' },
  { value: 'MN', label: 'Mongolija' },
  { value: 'ME', label: 'Juodkalnija' },
  { value: 'MS', label: 'Montseratas' },
  { value: 'MA', label: 'Marokas' },
  { value: 'MZ', label: 'Mozambikas' },
  { value: 'MM', label: 'Mianmaras' },
  { value: 'NA', label: 'Namibija' },
  { value: 'NR', label: 'Nauru' },
  { value: 'NP', label: 'Nepalas' },
  { value: 'NL', label: 'Nyderlandai' },
  { value: 'NC', label: 'Naujoji Kaledonija' },
  { value: 'NZ', label: 'Naujoji Zelandija' },
  { value: 'NI', label: 'Nikaragva' },
  { value: 'NE', label: 'Nigeris' },
  { value: 'NG', label: 'Nigerija' },
  { value: 'NU', label: 'Niujė' },
  { value: 'NF', label: 'Norfolko Sala' },
  { value: 'MP', label: 'Marianos Šiaurinės Salos' },
  { value: 'NO', label: 'Norvegija' },
  { value: 'OM', label: 'Omanas' },
  { value: 'PK', label: 'Pakistanas' },
  { value: 'PW', label: 'Palau' },
  { value: 'PS', label: 'Palestinos Teritorija' },
  { value: 'PA', label: 'Panama' },
  { value: 'PG', label: 'Papua Naujoji Gvinėja' },
  { value: 'PY', label: 'Paragvajus' },
  { value: 'PE', label: 'Peru' },
  { value: 'PH', label: 'Filipinai' },
  { value: 'PN', label: 'Pitkerno Salos' },
  { value: 'PL', label: 'Lenkija' },
  { value: 'PT', label: 'Portugalija' },
  { value: 'PR', label: 'Puerto Rikas' },
  { value: 'QA', label: 'Kataras' },
  { value: 'MK', label: 'Šiaurės Makedonija' },
  { value: 'RO', label: 'Rumunija' },
  { value: 'RU', label: 'Rusija (teroristinė valstybė)' },
  { value: 'RW', label: 'Ruanda' },
  { value: 'RE', label: 'Reunjonas' },
  { value: 'BL', label: 'Sen Bartelemi' },
  { value: 'SH', label: 'Šv. Elenos Sala' },
  { value: 'KN', label: 'Sent Kitsas ir Nevis' },
  { value: 'LC', label: 'Sent Lusija' },
  { value: 'MF', label: 'Sen Martenas (Prancūzijos dalis)' },
  { value: 'PM', label: 'Sen Pjeras ir Mikelonas' },
  { value: 'VC', label: 'Sent Vinsentas ir Grenadinai' },
  { value: 'WS', label: 'Samoa' },
  { value: 'SM', label: 'San Marinas' },
  { value: 'ST', label: 'San Tomė ir Prinsipė' },
  { value: 'SA', label: 'Saudo Arabija' },
  { value: 'SN', label: 'Senegalas' },
  { value: 'RS', label: 'Serbija' },
  { value: 'SC', label: 'Seišeliai' },
  { value: 'SL', label: 'Siera Leonė' },
  { value: 'SG', label: 'Singapūras' },
  { value: 'SX', label: 'Sint Martenas (Nyderlandų dalis)' },
  { value: 'SK', label: 'Slovakija' },
  { value: 'SI', label: 'Slovėnija' },
  { value: 'SB', label: 'Saliamono Salos' },
  { value: 'SO', label: 'Somalis' },
  { value: 'ZA', label: 'Pietų Afrika' },
  { value: 'GS', label: 'Pietų Džordžijos ir Pietų Sandvičo Salos' },
  { value: 'SS', label: 'Pietų Sudanas' },
  { value: 'ES', label: 'Ispanija' },
  { value: 'LK', label: 'Šri Lanka' },
  { value: 'SD', label: 'Sudanas' },
  { value: 'SR', label: 'Surinamas' },
  { value: 'SJ', label: 'Svalbardas ir Jan Majenas' },
  { value: 'SE', label: 'Švedija' },
  { value: 'CH', label: 'Šveicarija' },
  { value: 'SY', label: 'Sirija' },
  { value: 'TW', label: 'Taivanas' },
  { value: 'TJ', label: 'Tadžikistanas' },
  { value: 'TZ', label: 'Tanzanija' },
  { value: 'TH', label: 'Tailandas' },
  { value: 'TL', label: 'Rytų Timoras' },
  { value: 'TG', label: 'Togas' },
  { value: 'TK', label: 'Tokelau' },
  { value: 'TO', label: 'Tonga' },
  { value: 'TT', label: 'Trinidadas ir Tobagas' },
  { value: 'TN', label: 'Tunisas' },
  { value: 'TR', label: 'Turkija' },
  { value: 'TM', label: 'Turkmėnistanas' },
  { value: 'TC', label: 'Terkso ir Kaikoso Salos' },
  { value: 'TV', label: 'Tuvalu' },
  { value: 'UG', label: 'Uganda' },
  { value: 'UA', label: 'Ukraina' },
  { value: 'AE', label: 'Jungtiniai Arabų Emyratai' },
  { value: 'GB', label: 'Jungtinė Karalystė' },
  { value: 'UM', label: 'Jungtinių Valstijų Mažosios Tolimosios Salos' },
  { value: 'US', label: 'JAV' },
  { value: 'UY', label: 'Urugvajus' },
  { value: 'UZ', label: 'Uzbekistanas' },
  { value: 'VU', label: 'Vanuatu' },
  { value: 'VE', label: 'Venesuela' },
  { value: 'VN', label: 'Vietnamas' },
  { value: 'VG', label: 'Mergelių Salos (Didžioji Britanija)' },
  { value: 'VI', label: 'Mergelių Salos (JAV)' },
  { value: 'WF', label: 'Volisas ir Futūna' },
  { value: 'EH', label: 'Vakarų Sachara' },
  { value: 'YE', label: 'Jemenas' },
  { value: 'ZM', label: 'Zambija' },
  { value: 'ZW', label: 'Zimbabvė' },
  { value: 'OTHER', label: 'Kita / Nenurodyta' }
];

const otherOption = unsortedCountries.find(c => c.value === 'OTHER');
const sortedCountries = unsortedCountries
  .filter(c => c.value !== 'OTHER')
  .sort((a, b) => a.label.localeCompare(b.label, 'lt'));

if (otherOption) {
  sortedCountries.push(otherOption);
}
export const countries: { value: string, label: string }[] = sortedCountries;


export const detailedReportCategories: DetailedCategory[] = [
  {
    id: "fuel_theft",
    nameKey: "categories.fuel_theft",
    tags: ["kuro_vagyste", "krovinio_vagyste", "imones_turto_vagyste", "kita_tag"],
  },
  {
    id: "driving_safety",
    nameKey: "categories.driving_safety",
    tags: ["avaringumas", "pavojingas_vairavimas", "dazni_ket_pazeidimai", "kita_tag"],
  },
  {
    id: "behavior",
    nameKey: "categories.behavior",
    tags: [
      "grasinimai_agresija",
      "netinkamas_elgesys_kolegu_atzvilgiu",
      "psichotropiniu_medziagu_vartojimas",
      "konfliktiskas_asmuo",
      "neblaivus_darbo_metu",
      "kita_tag"
    ],
  },
  {
    id: "discipline",
    nameKey: "categories.discipline",
    tags: [
      "neatvykimas_i_darba_be_pateisinamos_priezasties",
      "neatsakingas_poziuris_i_darba",
      "kita_tag"
    ],
  },
  {
    id: "technical_damage",
    nameKey: "categories.technical_damage",
    tags: [
      "techninis_neatsakingumas",
      "rizika_saugumui_ar_kroviniui",
      "dazni_transporto_priemones_pazeidimai",
      "kita_tag"
    ],
  },
  {
    id: "legal_reputation",
    nameKey: "categories.legal_reputation",
    tags: [
      "buvo_teisinis_procesas_darbo_gincas",
      "pakenkta_imones_reputacijai",
      "neteiseta_veikla_itariama",
      "kita_tag"
    ],
  },
  {
    id: "other_category",
    nameKey: "categories.other_category",
    tags: [], 
  },
];

export const DESTRUCTIVE_REPORT_MAIN_CATEGORIES: string[] = ['fuel_theft', 'discipline', 'technical_damage', 'driving_safety'];

    

    